### ISSUE TITLE
Blender Error

### ISSUE THREAD

**Issue by Arsenal006** [MjTs140914/PES_Stadium_Exporter#2]
Blender Error
Error: FMDL format doesn't support
How to solve this problem?

**Comment by MjTs140914** [comment]
You need fix FMDL file use unity, after fix done you can import to blender...

here my friend **captain8lunt** in evo-web create tutorial how to fix this problem https://youtu.be/5LwVbsw-fas

**Comment by Arsenal006** [comment]
> 您需要修复FMDL文件使用统一，修复完成后您可以导入到搅拌机...
> 
> 在这里，我的朋友**队长8lunt**在evo-web中创建教程如何解决此问题 https://youtu.be/5LwVbsw-fas

I am using PES_ Stadium_ Exporter plug-in reported an error.
Is this the only way to solve this problem?

**Comment by MjTs140914** [comment]
yes only this way to fix problem, this is not about tools problem, but fmdl file the problem.

**Comment by Arsenal006** [comment]
> 是的，只有这种方式来解决问题，这不是关于工具问题，而是fmdl文件的问题。

I see. Thank you very much for your patience answer!
